name: bwt
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.13
  - numpy
  - numba
  - cython
  - pytest
  - matplotlib
  - pip
  - trf
  - setuptools
  - mreps
  - pip:
      - pydivsufsort
      - matplotlib-venn
